import sqlite3
from contextlib import closing


class DbManager:
    def __init__(self) -> None:
        self.db_name = "todo_app.db"

    def insert_task(self, task_name: str, task_status: str) -> int:
        """
        Inserts a new task in the database. Returns the autogenerated task id.
        :param task_name: str
        :param task_status: str
        :return: int
        """
        params = [task_name, task_status]
        sql = "INSERT INTO tasks (name,status) VALUES (?,?)"
        with closing(sqlite3.connect(self.db_name)) as con, con, closing(
            con.cursor()
        ) as cur:
            cur.execute(sql, params)
            return cur.lastrowid
